const constants = {
  GET_ALL_FAILURE: 'TRAIN/GET_ALL/FAILURE',
  GET_ALL_REQUEST: 'TRAIN/GET_ALL/REQUEST',
  GET_ALL_SUCCESS: 'TRAIN/GET_ALL/SUCCESS',
  GET_LATEST_FAILURE: 'TRAIN/GET_LATEST/FAILURE',
  GET_LATEST_REQUEST: 'TRAIN/GET_LATEST/REQUEST',
  GET_LATEST_SUCCESS: 'TRAIN/GET_LATEST/SUCCESS',
};

export default constants;
